"""vendor service re migration

Revision ID: 0ffc89c78e0d
Revises: 2d5936ace655
Create Date: 2025-03-29 01:47:00.974624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ffc89c78e0d'
down_revision: Union[str, None] = '2d5936ace655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('is_temporary', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('last_login', sa.DateTime(), nullable=True))
    
    # Modified gender enum alteration with USING clause
    op.execute('ALTER TABLE vendors ALTER COLUMN gender TYPE gender USING gender::text::gender')
    
    # Modified marital_status enum alteration with USING clause
    op.execute('ALTER TABLE vendors ALTER COLUMN marital_status TYPE maritalstatus USING marital_status::text::maritalstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Modified marital_status enum reversion with USING clause
    op.execute('ALTER TABLE vendors ALTER COLUMN marital_status TYPE vendor_maritalstatus USING marital_status::text::vendor_maritalstatus')
    
    # Modified gender enum reversion with USING clause
    op.execute('ALTER TABLE vendors ALTER COLUMN gender TYPE vendor_gender USING gender::text::vendor_gender')
    
    op.drop_column('vendors', 'last_login')
    op.drop_column('vendors', 'is_temporary')
    # ### end Alembic commands ###
