"""add employee constraint

Revision ID: 2d871a8a78ca
Revises: 3e5b2bab821b
Create Date: 2025-04-14 22:03:22.477686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d871a8a78ca'
down_revision: Union[str, None] = '3e5b2bab821b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('employee_hdr_email_key', 'employee_hdr', ['email'])
    op.create_unique_constraint('employee_hdr_employee_code_key', 'employee_hdr', ['employee_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_hdr_employee_code_key', 'employee_hdr', type_='unique')
    op.drop_constraint('employee_hdr_email_key', 'employee_hdr', type_='unique')
    # ### end Alembic commands ###
