"""country service migration

Revision ID: 33f63853ceb6
Revises: be1023da9c7f
Create Date: 2025-03-24 00:58:25.506888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33f63853ceb6'
down_revision: Union[str, None] = 'be1023da9c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_country_access')
    op.add_column('country_hdr', sa.Column('currency', sa.String(length=50), nullable=True))
    op.add_column('country_hdr', sa.Column('official_language', sa.String(length=100), nullable=True))
    op.add_column('country_hdr', sa.Column('description', sa.String(), nullable=True))
    op.add_column('visa_process_hdr', sa.Column('visa_description', sa.Text(), nullable=True))
    op.add_column('visa_process_hdr', sa.Column('vendor_commission', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('visa_rate_cut', sa.Column('government_fee', sa.Integer(), nullable=False))
    op.add_column('visa_rate_cut', sa.Column('service_fee', sa.Integer(), nullable=False))
    op.add_column('visa_rate_cut', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('visa_rate_cut', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('visa_rate_cut', sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('visa_rate_cut', 'process_fee')
    op.drop_column('visa_rate_cut', 'applicable_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visa_rate_cut', sa.Column('applicable_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('visa_rate_cut', sa.Column('process_fee', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('visa_rate_cut', 'created_date')
    op.drop_column('visa_rate_cut', 'is_default')
    op.drop_column('visa_rate_cut', 'start_date')
    op.drop_column('visa_rate_cut', 'service_fee')
    op.drop_column('visa_rate_cut', 'government_fee')
    op.drop_column('visa_process_hdr', 'vendor_commission')
    op.drop_column('visa_process_hdr', 'visa_description')
    op.drop_column('country_hdr', 'description')
    op.drop_column('country_hdr', 'official_language')
    op.drop_column('country_hdr', 'currency')
    op.create_table('employee_country_access',
    sa.Column('country_access_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('granted_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country_hdr.country_id'], name='employee_country_access_country_id_fkey'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_hdr.employee_id'], name='employee_country_access_employee_id_fkey'),
    sa.ForeignKeyConstraint(['granted_by'], ['employee_hdr.employee_id'], name='employee_country_access_granted_by_fkey'),
    sa.PrimaryKeyConstraint('country_access_id', name='employee_country_access_pkey')
    )
    # ### end Alembic commands ###
