"""coupon migration

Revision ID: 430190692992
Revises: 0ffc89c78e0d
Create Date: 2025-04-09 02:48:50.389697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430190692992'
down_revision: Union[str, None] = '0ffc89c78e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('coupon_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('FLAT', 'PERCENTAGE', name='coupontypeenum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('min_purchase_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('coupon_id'),
    sa.UniqueConstraint('coupon_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons')
    # ### end Alembic commands ###
