"""vendor approve at migration

Revision ID: 5f71f6eedeed
Revises: 9be766aa5864
Create Date: 2025-04-17 01:36:20.319459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f71f6eedeed'
down_revision: Union[str, None] = '9be766aa5864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_documents', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_documents', 'approved_at')
    # ### end Alembic commands ###
