"""Add initial countries

Revision ID: 847a4304515e
Revises: 6552e2e5f2c2
Create Date: 2025-03-15 19:39:50.337610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '847a4304515e'
down_revision: Union[str, None] = '6552e2e5f2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Comprehensive list of countries (ISO 3166-1 alpha-3 codes)
countries_data = [
    {"country_name": "Afghanistan", "country_code": "AFG"},
    {"country_name": "Albania", "country_code": "ALB"},
    {"country_name": "Algeria", "country_code": "DZA"},
    {"country_name": "Andorra", "country_code": "AND"},
    {"country_name": "Angola", "country_code": "AGO"},
    {"country_name": "Antigua and Barbuda", "country_code": "ATG"},
    {"country_name": "Argentina", "country_code": "ARG"},
    {"country_name": "Armenia", "country_code": "ARM"},
    {"country_name": "Australia", "country_code": "AUS"},
    {"country_name": "Austria", "country_code": "AUT"},
    {"country_name": "Azerbaijan", "country_code": "AZE"},
    {"country_name": "Bahamas", "country_code": "BHS"},
    {"country_name": "Bahrain", "country_code": "BHR"},
    {"country_name": "Bangladesh", "country_code": "BGD"},
    {"country_name": "Barbados", "country_code": "BRB"},
    {"country_name": "Belarus", "country_code": "BLR"},
    {"country_name": "Belgium", "country_code": "BEL"},
    {"country_name": "Belize", "country_code": "BLZ"},
    {"country_name": "Benin", "country_code": "BEN"},
    {"country_name": "Bhutan", "country_code": "BTN"},
    {"country_name": "Bolivia", "country_code": "BOL"},
    {"country_name": "Bosnia and Herzegovina", "country_code": "BIH"},
    {"country_name": "Botswana", "country_code": "BWA"},
    {"country_name": "Brazil", "country_code": "BRA"},
    {"country_name": "Brunei", "country_code": "BRN"},
    {"country_name": "Bulgaria", "country_code": "BGR"},
    {"country_name": "Burkina Faso", "country_code": "BFA"},
    {"country_name": "Burundi", "country_code": "BDI"},
    {"country_name": "Cabo Verde", "country_code": "CPV"},
    {"country_name": "Cambodia", "country_code": "KHM"},
    {"country_name": "Cameroon", "country_code": "CMR"},
    {"country_name": "Canada", "country_code": "CAN"},
    {"country_name": "Central African Republic", "country_code": "CAF"},
    {"country_name": "Chad", "country_code": "TCD"},
    {"country_name": "Chile", "country_code": "CHL"},
    {"country_name": "China", "country_code": "CHN"},
    {"country_name": "Colombia", "country_code": "COL"},
    {"country_name": "Comoros", "country_code": "COM"},
    {"country_name": "Congo (Brazzaville)", "country_code": "COG"},
    {"country_name": "Congo (Kinshasa)", "country_code": "COD"},
    {"country_name": "Costa Rica", "country_code": "CRI"},
    {"country_name": "Croatia", "country_code": "HRV"},
    {"country_name": "Cuba", "country_code": "CUB"},
    {"country_name": "Cyprus", "country_code": "CYP"},
    {"country_name": "Czechia", "country_code": "CZE"},
    {"country_name": "Denmark", "country_code": "DNK"},
    {"country_name": "Djibouti", "country_code": "DJI"},
    {"country_name": "Dominica", "country_code": "DMA"},
    {"country_name": "Dominican Republic", "country_code": "DOM"},
    {"country_name": "Ecuador", "country_code": "ECU"},
    {"country_name": "Egypt", "country_code": "EGY"},
    {"country_name": "El Salvador", "country_code": "SLV"},
    {"country_name": "Equatorial Guinea", "country_code": "GNQ"},
    {"country_name": "Eritrea", "country_code": "ERI"},
    {"country_name": "Estonia", "country_code": "EST"},
    {"country_name": "Eswatini", "country_code": "SWZ"},
    {"country_name": "Ethiopia", "country_code": "ETH"},
    {"country_name": "Fiji", "country_code": "FJI"},
    {"country_name": "Finland", "country_code": "FIN"},
    {"country_name": "France", "country_code": "FRA"},
    {"country_name": "Gabon", "country_code": "GAB"},
    {"country_name": "Gambia", "country_code": "GMB"},
    {"country_name": "Georgia", "country_code": "GEO"},
    {"country_name": "Germany", "country_code": "DEU"},
    {"country_name": "Ghana", "country_code": "GHA"},
    {"country_name": "Greece", "country_code": "GRC"},
    {"country_name": "Grenada", "country_code": "GRD"},
    {"country_name": "Guatemala", "country_code": "GTM"},
    {"country_name": "Guinea", "country_code": "GIN"},
    {"country_name": "Guinea-Bissau", "country_code": "GNB"},
    {"country_name": "Guyana", "country_code": "GUY"},
    {"country_name": "Haiti", "country_code": "HTI"},
    {"country_name": "Honduras", "country_code": "HND"},
    {"country_name": "Hungary", "country_code": "HUN"},
    {"country_name": "Iceland", "country_code": "ISL"},
    {"country_name": "India", "country_code": "IND"},
    {"country_name": "Indonesia", "country_code": "IDN"},
    {"country_name": "Iran", "country_code": "IRN"},
    {"country_name": "Iraq", "country_code": "IRQ"},
    {"country_name": "Ireland", "country_code": "IRL"},
    {"country_name": "Israel", "country_code": "ISR"},
    {"country_name": "Italy", "country_code": "ITA"},
    {"country_name": "Jamaica", "country_code": "JAM"},
    {"country_name": "Japan", "country_code": "JPN"},
    {"country_name": "Jordan", "country_code": "JOR"},
    {"country_name": "Kazakhstan", "country_code": "KAZ"},
    {"country_name": "Kenya", "country_code": "KEN"},
    {"country_name": "Kiribati", "country_code": "KIR"},
    {"country_name": "Kuwait", "country_code": "KWT"},
    {"country_name": "Kyrgyzstan", "country_code": "KGZ"},
    {"country_name": "Laos", "country_code": "LAO"},
    {"country_name": "Latvia", "country_code": "LVA"},
    {"country_name": "Lebanon", "country_code": "LBN"},
    {"country_name": "Lesotho", "country_code": "LSO"},
    {"country_name": "Liberia", "country_code": "LBR"},
    {"country_name": "Libya", "country_code": "LBY"},
    {"country_name": "Liechtenstein", "country_code": "LIE"},
    {"country_name": "Lithuania", "country_code": "LTU"},
    {"country_name": "Luxembourg", "country_code": "LUX"},
    {"country_name": "Madagascar", "country_code": "MDG"},
    {"country_name": "Malawi", "country_code": "MWI"},
    {"country_name": "Malaysia", "country_code": "MYS"},
    {"country_name": "Maldives", "country_code": "MDV"},
    {"country_name": "Mali", "country_code": "MLI"},
    {"country_name": "Malta", "country_code": "MLT"},
    {"country_name": "Marshall Islands", "country_code": "MHL"},
    {"country_name": "Mauritania", "country_code": "MRT"},
    {"country_name": "Mauritius", "country_code": "MUS"},
    {"country_name": "Mexico", "country_code": "MEX"},
    {"country_name": "Micronesia", "country_code": "FSM"},
    {"country_name": "Moldova", "country_code": "MDA"},
    {"country_name": "Monaco", "country_code": "MCO"},
    {"country_name": "Mongolia", "country_code": "MNG"},
    {"country_name": "Montenegro", "country_code": "MNE"},
    {"country_name": "Morocco", "country_code": "MAR"},
    {"country_name": "Mozambique", "country_code": "MOZ"},
    {"country_name": "Myanmar", "country_code": "MMR"},
    {"country_name": "Namibia", "country_code": "NAM"},
    {"country_name": "Nauru", "country_code": "NRU"},
    {"country_name": "Nepal", "country_code": "NPL"},
    {"country_name": "Netherlands", "country_code": "NLD"},
    {"country_name": "New Zealand", "country_code": "NZL"},
    {"country_name": "Nicaragua", "country_code": "NIC"},
    {"country_name": "Niger", "country_code": "NER"},
    {"country_name": "Nigeria", "country_code": "NGA"},
    {"country_name": "North Korea", "country_code": "PRK"},
    {"country_name": "North Macedonia", "country_code": "MKD"},
    {"country_name": "Norway", "country_code": "NOR"},
    {"country_name": "Oman", "country_code": "OMN"},
    {"country_name": "Pakistan", "country_code": "PAK"},
    {"country_name": "Palau", "country_code": "PLW"},
    {"country_name": "Panama", "country_code": "PAN"},
    {"country_name": "Papua New Guinea", "country_code": "PNG"},
    {"country_name": "Paraguay", "country_code": "PRY"},
    {"country_name": "Peru", "country_code": "PER"},
    {"country_name": "Philippines", "country_code": "PHL"},
    {"country_name": "Poland", "country_code": "POL"},
    {"country_name": "Portugal", "country_code": "PRT"},
    {"country_name": "Qatar", "country_code": "QAT"},
    {"country_name": "Romania", "country_code": "ROU"},
    {"country_name": "Russia", "country_code": "RUS"},
    {"country_name": "Rwanda", "country_code": "RWA"},
    {"country_name": "Saint Kitts and Nevis", "country_code": "KNA"},
    {"country_name": "Saint Lucia", "country_code": "LCA"},
    {"country_name": "Saint Vincent and the Grenadines", "country_code": "VCT"},
    {"country_name": "Samoa", "country_code": "WSM"},
    {"country_name": "San Marino", "country_code": "SMR"},
    {"country_name": "Sao Tome and Principe", "country_code": "STP"},
    {"country_name": "Saudi Arabia", "country_code": "SAU"},
    {"country_name": "Senegal", "country_code": "SEN"},
    {"country_name": "Serbia", "country_code": "SRB"},
    {"country_name": "Seychelles", "country_code": "SYC"},
    {"country_name": "Sierra Leone", "country_code": "SLE"},
    {"country_name": "Singapore", "country_code": "SGP"},
    {"country_name": "Slovakia", "country_code": "SVK"},
    {"country_name": "Slovenia", "country_code": "SVN"},
    {"country_name": "Solomon Islands", "country_code": "SLB"},
    {"country_name": "Somalia", "country_code": "SOM"},
    {"country_name": "South Africa", "country_code": "ZAF"},
    {"country_name": "South Korea", "country_code": "KOR"},
    {"country_name": "South Sudan", "country_code": "SSD"},
    {"country_name": "Spain", "country_code": "ESP"},
    {"country_name": "Sri Lanka", "country_code": "LKA"},
    {"country_name": "Sudan", "country_code": "SDN"},
    {"country_name": "Suriname", "country_code": "SUR"},
    {"country_name": "Sweden", "country_code": "SWE"},
    {"country_name": "Switzerland", "country_code": "CHE"},
    {"country_name": "Syria", "country_code": "SYR"},
    {"country_name": "Taiwan", "country_code": "TWN"},
    {"country_name": "Tajikistan", "country_code": "TJK"},
    {"country_name": "Tanzania", "country_code": "TZA"},
    {"country_name": "Thailand", "country_code": "THA"},
    {"country_name": "Timor-Leste", "country_code": "TLS"},
    {"country_name": "Togo", "country_code": "TGO"},
    {"country_name": "Tonga", "country_code": "TON"},
    {"country_name": "Trinidad and Tobago", "country_code": "TTO"},
    {"country_name": "Tunisia", "country_code": "TUN"},
    {"country_name": "Turkey", "country_code": "TUR"},
    {"country_name": "Turkmenistan", "country_code": "TKM"},
    {"country_name": "Tuvalu", "country_code": "TUV"},
    {"country_name": "Uganda", "country_code": "UGA"},
    {"country_name": "Ukraine", "country_code": "UKR"},
    {"country_name": "United Arab Emirates", "country_code": "ARE"},
    {"country_name": "United Kingdom", "country_code": "GBR"},
    {"country_name": "United States of America", "country_code": "USA"},
    {"country_name": "Uruguay", "country_code": "URY"},
    {"country_name": "Uzbekistan", "country_code": "UZB"},
    {"country_name": "Vanuatu", "country_code": "VUT"},
    {"country_name": "Venezuela", "country_code": "VEN"},
    {"country_name": "Vietnam", "country_code": "VNM"},
    {"country_name": "Yemen", "country_code": "YEM"},
    {"country_name": "Zambia", "country_code": "ZMB"},
    {"country_name": "Zimbabwe", "country_code": "ZWE"},
]

def upgrade():
    country_table = sa.table(
        'country_hdr',
        sa.column('country_name', sa.String),
        sa.column('country_code', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('logo_path', sa.String),
        sa.column('created_date', sa.DateTime)
    )

    op.bulk_insert(
        country_table,
        [
            {
                "country_name": country["country_name"],
                "country_code": country["country_code"],
                "is_active": False,
                "logo_path": None,
                "created_date": datetime.now()
            }
            for country in countries_data
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    pass
