"""vendor free remarks add

Revision ID: 9be766aa5864
Revises: fdaf6358494b
Create Date: 2025-04-16 01:44:02.402690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be766aa5864'
down_revision: Union[str, None] = 'fdaf6358494b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_documents', sa.Column('remarks', sa.String(length=255), nullable=True))
    op.add_column('vendors', sa.Column('remarks', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'remarks')
    op.drop_column('vendor_documents', 'remarks')
    # ### end Alembic commands ###
