"""fix ambiguous foreign keys in EmployeeHdr

Revision ID: c96e469263cd
Revises: d28922771492
Create Date: 2025-03-16 22:55:24.166736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96e469263cd'
down_revision: Union[str, None] = 'd28922771492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the new enum types
    gender_enum = sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender')
    marital_status_enum = sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatus')
    id_proof_type_enum = sa.Enum('AADHAR', 'PAN', 'VOTER_ID', 'DRIVING_LICENSE', 'PASSPORT', 'OTHER', name='idprooftype')

    gender_enum.create(op.get_bind(), checkfirst=True)
    marital_status_enum.create(op.get_bind(), checkfirst=True)
    id_proof_type_enum.create(op.get_bind(), checkfirst=True)

    # Alter the columns with explicit casting
    op.execute('ALTER TABLE employee_hdr ALTER COLUMN gender TYPE gender USING gender::text::gender')
    op.execute('ALTER TABLE employee_hdr ALTER COLUMN marital_status TYPE maritalstatus USING marital_status::text::maritalstatus')
    op.execute('ALTER TABLE employee_hdr ALTER COLUMN id_proof_type TYPE idprooftype USING id_proof_type::text::idprooftype')

    # Drop the old enum types
    op.execute("DROP TYPE IF EXISTS employee_gender_enum")
    op.execute("DROP TYPE IF EXISTS employee_marital_status_enum")
    op.execute("DROP TYPE IF EXISTS employee_id_proof_type_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the old enum types
    gender_enum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='employee_gender_enum')
    marital_status_enum = postgresql.ENUM('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='employee_marital_status_enum')
    id_proof_type_enum = postgresql.ENUM('AADHAR', 'PAN', 'VOTER_ID', 'DRIVING_LICENSE', 'PASSPORT', 'OTHER', name='employee_id_proof_type_enum')

    gender_enum.create(op.get_bind(), checkfirst=True)
    marital_status_enum.create(op.get_bind(), checkfirst=True)
    id_proof_type_enum.create(op.get_bind(), checkfirst=True)

    # Alter the columns with explicit casting
    op.execute('ALTER TABLE employee_hdr ALTER COLUMN gender TYPE employee_gender_enum USING gender::text::employee_gender_enum')
    op.execute('ALTER TABLE employee_hdr ALTER COLUMN marital_status TYPE employee_marital_status_enum USING marital_status::text::employee_marital_status_enum')
    op.execute('ALTER TABLE employee_hdr ALTER COLUMN id_proof_type TYPE employee_id_proof_type_enum USING id_proof_type::text::employee_id_proof_type_enum')

    # Drop the new enum types
    op.execute("DROP TYPE IF EXISTS gender")
    op.execute("DROP TYPE IF EXISTS maritalstatus")
    op.execute("DROP TYPE IF EXISTS idprooftype")
    # ### end Alembic commands ###
