"""Enum Update

Revision ID: fdaf6358494b
Revises: 2d871a8a78ca
Create Date: 2025-04-16 00:58:22.073514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdaf6358494b'
down_revision: Union[str, None] = '2d871a8a78ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update VendorStatus enum
    op.execute("ALTER TYPE vendorstatus RENAME TO vendorstatus_old")
    op.execute("""
        CREATE TYPE vendorstatus AS ENUM (
            'TEMPORARY',
            'PENDING',
            'APPROVED',
            'REJECTED',
            'SUSPENDED',
            'HOLD',
            'BLACKLISTED'
        )
    """)
    op.execute("""
        ALTER TABLE vendors 
        ALTER COLUMN status TYPE vendorstatus USING status::text::vendorstatus
    """)
    op.execute("DROP TYPE vendorstatus_old")
    
    # Update DocumentType enum
    op.execute("ALTER TYPE documenttype RENAME TO documenttype_old")
    op.execute("""
        CREATE TYPE documenttype AS ENUM (
            'AADHAR',
            'PAN',
            'GST',
            'PASSPORT',
            'DRIVING_LICENSE',
            'VOTER_ID',
            'MOU',
            'BANK_STATEMENT',
            'OTHER'
        )
    """)
    op.execute("""
        ALTER TABLE vendor_documents 
        ALTER COLUMN document_type TYPE documenttype USING document_type::text::documenttype
    """)
    op.execute("DROP TYPE documenttype_old")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert DocumentType enum
    op.execute("ALTER TYPE documenttype RENAME TO documenttype_new")
    op.execute("""
        CREATE TYPE documenttype AS ENUM (
            'AADHAR',
            'PAN',
            'GST',
            'PASSPORT',
            'DRIVING_LICENSE',
            'VOTER_ID',
            'MOU',
            'OTHER'
        )
    """)
    op.execute("""
        ALTER TABLE vendor_documents 
        ALTER COLUMN document_type TYPE documenttype USING document_type::text::documenttype
    """)
    op.execute("DROP TYPE documenttype_new")
    
    # Revert VendorStatus enum
    op.execute("ALTER TYPE vendorstatus RENAME TO vendorstatus_new")
    op.execute("""
        CREATE TYPE vendorstatus AS ENUM (
            'PENDING',
            'APPROVED',
            'REJECTED',
            'SUSPENDED',
            'HOLD',
            'BLACKLISTED'
        )
    """)
    op.execute("""
        ALTER TABLE vendors 
        ALTER COLUMN status TYPE vendorstatus USING status::text::vendorstatus
    """)
    op.execute("DROP TYPE vendorstatus_new")
    
    # ### end Alembic commands ###