# app/core/constants.py
from enum import Enum

USER_TYPE_EMPLOYEE = "employee"
USER_TYPE_USER = "user"

ROUTE_PREFIX_USERS = "/users"
ROUTE_PREFIX_EMPLOYEES = "/employees"
ROUTE_PREFIX_COUNTRIES = "/countries"
ROUTE_PREFIX_COMMON = "/api"
ROUTE_PREFIX_ROLES = "/roles"
ROUTE_PREFIX_VISA = "/visa"

class UserType(str, Enum):
    EMPLOYEE = USER_TYPE_EMPLOYEE
    USER = USER_TYPE_USER

ACCESS_RULES = {
    USER_TYPE_USER: [ROUTE_PREFIX_USERS, ROUTE_PREFIX_COMMON, ROUTE_PREFIX_COUNTRIES, ROUTE_PREFIX_VISA],
    USER_TYPE_EMPLOYEE: [ROUTE_PREFIX_USERS, ROUTE_PREFIX_EMPLOYEES, ROUTE_PREFIX_COUNTRIES, ROUTE_PREFIX_COMMON, ROUTE_PREFIX_ROLES, ROUTE_PREFIX_VISA],
    # Add more user types and route prefixes as needed
}