# app/core/constants.py
from enum import Enum

USER_TYPE_EMPLOYEE = "employee"
USER_TYPE_USER = "user"
USER_TYPE_VENDOR = "vendor"

ROUTE_PREFIX_USERS = "/users"
ROUTE_PREFIX_EMPLOYEES = "/employees"
ROUTE_PREFIX_COUNTRIES = "/countries"
ROUTE_PREFIX_COMMON = "/api"
ROUTE_PREFIX_ROLES = "/roles"
ROUTE_PREFIX_VISA = "/visa"
ROUTE_PREFIX_VENDOR = "/vendors"
ROUTE_PREFIX_COUPON = "/coupons"

class UserType(str, Enum):
    EMPLOYEE = USER_TYPE_EMPLOYEE
    USER = USER_TYPE_USER
    VENDOR = USER_TYPE_VENDOR

ACCESS_RULES = {
    USER_TYPE_USER: [ROUTE_PREFIX_USERS, ROUTE_PREFIX_COMMON, ROUTE_PREFIX_COUNTRIES, ROUTE_PREFIX_VISA, ROUTE_PREFIX_COUPON],
    USER_TYPE_EMPLOYEE: [ROUTE_PREFIX_USERS, ROUTE_PREFIX_EMPLOYEES, ROUTE_PREFIX_COUNTRIES, ROUTE_PREFIX_COMMON, ROUTE_PREFIX_ROLES, ROUTE_PREFIX_VISA, ROUTE_PREFIX_VENDOR, ROUTE_PREFIX_COUPON],
    USER_TYPE_VENDOR: [ROUTE_PREFIX_VENDOR, ROUTE_PREFIX_COMMON, ROUTE_PREFIX_COUPON],
    # Add more user types and route prefixes as needed
}